// crud are basically a specialization of the db3 command system to support simple mutations.

import { z } from "zod";
import { defineCommand } from "./db3Command";
import type { AnyDB3Entity, EntityIdOf } from "./db3Entity";

const identityResultSchema = <TIdentitySchema extends z.ZodTypeAny>(
    identitySchema: TIdentitySchema,
) => z.object({
    identity: identitySchema,
}).strict();

// ensure that the given zod schema does not contain the server-owned identity fields
// `id` or `publicId` typically.
function requireWritableSchemasDoNotOwnIdentity(
    entity: AnyDB3Entity,
    schemaName: string,
    schema: z.AnyZodObject,
): void {
    const identityMembers = new Set([
        entity.schema.pkMember,
        entity.schema.publicIdMember,
    ].filter((member): member is string => !!member));

    const declaredIdentityMembers = //
        Object.keys(schema.shape)
            .filter(member => identityMembers.has(member));

    if (declaredIdentityMembers.length > 0) {
        throw new Error(
            `${entity.entityID} ${schemaName} must not declare server-owned identity fields: ${declaredIdentityMembers.join(", ")}.`,
        );
    }
}

function getDeleteType(entity: AnyDB3Entity): "softWhenPossible" | "hard" {
    switch (entity.schema.deletePolicy) {
        case "hard":
            return "hard";
        case "softOnly":
            return "softWhenPossible";
        case "disabled":
            throw new Error(`${entity.entityID} does not permit generated delete commands.`);
    }
}

/**
 * Defines the ordinary single-row write contract for an entity.
 *
 * The supplied schemas declare writable fields only. Identity is generated by
 * the server on create and travels separately from a present-keys-only patch on
 * update. The public DTOs therefore never expose xTable names, numeric table
 * IDs, or the legacy generic mutation envelope.
 */
export function defineEntityCrudCommands<
    TEntity extends AnyDB3Entity,
    TIdentitySchema extends z.ZodType<EntityIdOf<TEntity>>,
    TCreateSchema extends z.AnyZodObject,
    TUpdateFieldsSchema extends z.AnyZodObject,
>(args: {
    entity: TEntity;
    identitySchema: TIdentitySchema;
    createSchema: TCreateSchema;
    updateFieldsSchema: TUpdateFieldsSchema;
}) {
    requireWritableSchemasDoNotOwnIdentity(args.entity, "create schema", args.createSchema);

    // when updating, the patch object is separate from the "what to update" identity.
    // make sure the patch doesn't include it.
    requireWritableSchemasDoNotOwnIdentity(args.entity, "update schema", args.updateFieldsSchema);

    // Zod's methods on the AnyZodObject constraint widen the inferred shape;
    // preserve the caller's concrete DTO type while tightening runtime parsing.
    const createSchema = args.createSchema.strict() as TCreateSchema;
    const patchSchema: z.ZodType<Partial<z.infer<TUpdateFieldsSchema>>> = args
        .updateFieldsSchema
        .strict()
        .partial()
        .superRefine((patch, ctx) => {
            const presentEntries = Object.entries(patch);
            if (presentEntries.length === 0) {
                ctx.addIssue({
                    code: z.ZodIssueCode.custom,
                    message: "Update patch must contain at least one field.",
                });
            }
            for (const [fieldName, value] of presentEntries) {
                if (value !== undefined) continue;
                ctx.addIssue({
                    code: z.ZodIssueCode.custom,
                    path: [fieldName],
                    message: "Patch fields cannot be undefined; omit unchanged fields instead.",
                });
            }
        });
    const updateSchema = z.object({
        identity: args.identitySchema,
        patch: patchSchema,
    }).strict();
    const deleteSchema = z.object({
        identity: args.identitySchema,
    }).strict();
    const resultSchema = identityResultSchema(args.identitySchema);
    const invalidation = {
        mode: "caller" as const,
        entityIDs: [args.entity.entityID],
    };

    return {
        entity: args.entity,
        identitySchema: args.identitySchema,
        deleteType: getDeleteType(args.entity),
        createCommand: defineCommand({
            commandID: `${args.entity.entityID}_Create`,
            entity: args.entity,
            dtoSchema: createSchema,
            resultSchema,
            serialize: (input: z.infer<typeof createSchema>) => input,
            invalidation,
        }),
        updateCommand: defineCommand({
            commandID: `${args.entity.entityID}_Update`,
            entity: args.entity,
            dtoSchema: updateSchema,
            resultSchema,
            serialize: (input: z.infer<typeof updateSchema>) => input,
            invalidation,
        }),
        deleteCommand: defineCommand({
            commandID: `${args.entity.entityID}_Delete`,
            entity: args.entity,
            dtoSchema: deleteSchema,
            resultSchema,
            serialize: (input: z.infer<typeof deleteSchema>) => input,
            invalidation,
        }),
    } as const;
}

export type AnyDB3EntityCrudCommands = ReturnType<typeof defineEntityCrudCommands>;
