ALTER TABLE `User`
    ADD COLUMN `mergedIntoUserId` INTEGER NULL,
    ADD COLUMN `mergedAt` DATETIME(3) NULL,
    ADD CONSTRAINT `User_mergedIntoUserId_fkey` FOREIGN KEY (`mergedIntoUserId`) REFERENCES `User` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE;
