
export enum ActivityDetailTabId {
    general = "general",
    feature = "feature",
    user = "user",
    song = "song",
    event = "event",
    wikiPage = "wikiPage",
    file = "file",
    context = "context",
    attendance = "attendance",
    customLink = "customLink",
    //eventSegment = "eventSegment",
    setlist = "setlist",
    frontpageGalleryItem = "frontpageGalleryItem",
    menuLink = "menuLink",
    setlistPlan = "setlistPlan",
    songCreditType = "songCreditType",
    instrument = "instrument",
    screenSize = "screenSize",
    operatingSystem = "operatingSystem",
    pointerType = "pointerType",
    browser = "browser",
    deviceClass = "deviceClass",
    language = "language",
    locale = "locale",
    timezone = "timezone",
};