export interface DefaultRoleDefinition {
    name: string;
    description: string | null;
    isRoleForNewUsers: boolean;
    isPublicRole: boolean;
    isSysAdminRole: boolean;
    sortOrder: number;
    color: string | null;
    significance: string | null;
}

export const DefaultRoles: ReadonlyArray<DefaultRoleDefinition> =
    [
        {
            "name": "Public",
            "description": "not even logged in",
            "isRoleForNewUsers": false,
            "isPublicRole": true,
            "isSysAdminRole": false,
            "sortOrder": 0,
            "color": "citron",
            "significance": null
        },
        {
            "name": "Limited Users",
            "description": "logged-in users with no rights",
            "isRoleForNewUsers": true,
            "isPublicRole": false,
            "isSysAdminRole": false,
            "sortOrder": 10,
            "color": "green",
            "significance": null
        },
        {
            "name": "Normal Users",
            "description": "login with granted normal rights",
            "isRoleForNewUsers": false,
            "isPublicRole": false,
            "isSysAdminRole": false,
            "sortOrder": 40,
            "color": "blue",
            "significance": null
        },
        {
            "name": "Editors",
            "description": "",
            "isRoleForNewUsers": false,
            "isPublicRole": false,
            "isSysAdminRole": false,
            "sortOrder": 60,
            "color": "gold",
            "significance": null
        },
        {
            "name": "Moderators",
            "description": "site content moderation",
            "isRoleForNewUsers": false,
            "isPublicRole": false,
            "isSysAdminRole": false,
            "sortOrder": 80,
            "color": "purple",
            "significance": null
        },
        {
            "name": "Band Admin",
            "description": "technical band administration",
            "isRoleForNewUsers": false,
            "isPublicRole": false,
            "isSysAdminRole": false,
            "sortOrder": 90,
            "color": "purple",
            "significance": null
        },
        {
            "name": "Admin",
            "description": "technical admin",
            "isRoleForNewUsers": false,
            "isPublicRole": false,
            "isSysAdminRole": true,
            "sortOrder": 100,
            "color": "black",
            "significance": null
        }
    ];

// used by seeding, and by runtime permission seeds.
// use the role permission matrix page, copy as json and paste below to manage this.

export const DefaultRolePermissionAssignments: ReadonlyArray<[string, string]> =
    [
        ["Admin", "access_file_landing_page"],
        ["Admin", "admin_events"],
        ["Admin", "admin_files"],
        ["Admin", "admin_instruments"],
        ["Admin", "admin_songs"],
        ["Admin", "admin_wiki_pages"],
        ["Admin", "always_grant"],
        ["Admin", "assign_user_roles"],
        ["Admin", "change_others_event_responses"],
        ["Admin", "customize_menu"],
        ["Admin", "deactivate_users"],
        ["Admin", "edit_public_homepage"],
        ["Admin", "edit_wiki_pages"],
        ["Admin", "impersonate_user"],
        ["Admin", "login"],
        ["Admin", "manage_custom_links"],
        ["Admin", "manage_events"],
        ["Admin", "manage_files"],
        ["Admin", "manage_site_branding"],
        ["Admin", "manage_songs"],
        ["Admin", "manage_user_taxonomy"],
        ["Admin", "manage_users"],
        ["Admin", "merge_users"],
        ["Admin", "pin_song_recordings"],
        ["Admin", "practice_tools_use"],
        ["Admin", "public"],
        ["Admin", "recover_events"],
        ["Admin", "recover_files"],
        ["Admin", "recover_songs"],
        ["Admin", "recover_users"],
        ["Admin", "respond_to_events"],
        ["Admin", "search_users"],
        ["Admin", "search_wiki_pages"],
        ["Admin", "setlist_planner_access"],
        ["Admin", "sysadmin"],
        ["Admin", "upload_files"],
        ["Admin", "view_custom_links"],
        ["Admin", "view_events"],
        ["Admin", "view_events_nonpublic"],
        ["Admin", "view_events_reports"],
        ["Admin", "view_feature_reports"],
        ["Admin", "view_files"],
        ["Admin", "view_songs"],
        ["Admin", "view_user_contact_info"],
        ["Admin", "view_users_basic_info"],
        ["Admin", "view_wiki_page_revisions"],
        ["Admin", "view_wiki_pages"],
        ["Admin", "visibility_editors"],
        ["Admin", "visibility_logged_in_users"],
        ["Admin", "visibility_members"],
        ["Admin", "visibility_public"],
        ["Band Admin", "access_file_landing_page"],
        ["Band Admin", "admin_files"],
        ["Band Admin", "admin_songs"],
        ["Band Admin", "admin_wiki_pages"],
        ["Band Admin", "always_grant"],
        ["Band Admin", "assign_user_roles"],
        ["Band Admin", "change_others_event_responses"],
        ["Band Admin", "customize_menu"],
        ["Band Admin", "deactivate_users"],
        ["Band Admin", "edit_public_homepage"],
        ["Band Admin", "edit_wiki_pages"],
        ["Band Admin", "login"],
        ["Band Admin", "manage_custom_links"],
        ["Band Admin", "manage_events"],
        ["Band Admin", "manage_files"],
        ["Band Admin", "manage_site_branding"],
        ["Band Admin", "manage_songs"],
        ["Band Admin", "manage_user_taxonomy"],
        ["Band Admin", "manage_users"],
        ["Band Admin", "pin_song_recordings"],
        ["Band Admin", "practice_tools_use"],
        ["Band Admin", "public"],
        ["Band Admin", "respond_to_events"],
        ["Band Admin", "search_users"],
        ["Band Admin", "search_wiki_pages"],
        ["Band Admin", "upload_files"],
        ["Band Admin", "view_custom_links"],
        ["Band Admin", "view_events"],
        ["Band Admin", "view_events_nonpublic"],
        ["Band Admin", "view_events_reports"],
        ["Band Admin", "view_files"],
        ["Band Admin", "view_songs"],
        ["Band Admin", "view_user_contact_info"],
        ["Band Admin", "view_users_basic_info"],
        ["Band Admin", "view_wiki_page_revisions"],
        ["Band Admin", "view_wiki_pages"],
        ["Band Admin", "visibility_editors"],
        ["Band Admin", "visibility_logged_in_users"],
        ["Band Admin", "visibility_members"],
        ["Band Admin", "visibility_public"],
        ["Editors", "access_file_landing_page"],
        ["Editors", "always_grant"],
        ["Editors", "edit_public_homepage"],
        ["Editors", "edit_wiki_pages"],
        ["Editors", "login"],
        ["Editors", "manage_custom_links"],
        ["Editors", "manage_events"],
        ["Editors", "manage_files"],
        ["Editors", "manage_songs"],
        ["Editors", "pin_song_recordings"],
        ["Editors", "practice_tools_use"],
        ["Editors", "public"],
        ["Editors", "respond_to_events"],
        ["Editors", "search_users"],
        ["Editors", "search_wiki_pages"],
        ["Editors", "upload_files"],
        ["Editors", "view_custom_links"],
        ["Editors", "view_events"],
        ["Editors", "view_events_nonpublic"],
        ["Editors", "view_events_reports"],
        ["Editors", "view_files"],
        ["Editors", "view_songs"],
        ["Editors", "view_users_basic_info"],
        ["Editors", "view_wiki_page_revisions"],
        ["Editors", "view_wiki_pages"],
        ["Editors", "visibility_editors"],
        ["Editors", "visibility_logged_in_users"],
        ["Editors", "visibility_members"],
        ["Editors", "visibility_public"],
        ["Limited Users", "always_grant"],
        ["Limited Users", "login"],
        ["Limited Users", "practice_tools_use"],
        ["Limited Users", "public"],
        ["Limited Users", "view_events"],
        ["Limited Users", "view_files"],
        ["Limited Users", "view_wiki_pages"],
        ["Limited Users", "visibility_logged_in_users"],
        ["Limited Users", "visibility_public"],
        ["Moderators", "access_file_landing_page"],
        ["Moderators", "admin_wiki_pages"],
        ["Moderators", "always_grant"],
        ["Moderators", "change_others_event_responses"],
        ["Moderators", "customize_menu"],
        ["Moderators", "edit_public_homepage"],
        ["Moderators", "edit_wiki_pages"],
        ["Moderators", "login"],
        ["Moderators", "manage_custom_links"],
        ["Moderators", "manage_events"],
        ["Moderators", "manage_files"],
        ["Moderators", "manage_songs"],
        ["Moderators", "manage_users"],
        ["Moderators", "pin_song_recordings"],
        ["Moderators", "practice_tools_use"],
        ["Moderators", "public"],
        ["Moderators", "respond_to_events"],
        ["Moderators", "search_users"],
        ["Moderators", "search_wiki_pages"],
        ["Moderators", "upload_files"],
        ["Moderators", "view_custom_links"],
        ["Moderators", "view_events"],
        ["Moderators", "view_events_nonpublic"],
        ["Moderators", "view_events_reports"],
        ["Moderators", "view_files"],
        ["Moderators", "view_songs"],
        ["Moderators", "view_user_contact_info"],
        ["Moderators", "view_users_basic_info"],
        ["Moderators", "view_wiki_page_revisions"],
        ["Moderators", "view_wiki_pages"],
        ["Moderators", "visibility_editors"],
        ["Moderators", "visibility_logged_in_users"],
        ["Moderators", "visibility_members"],
        ["Moderators", "visibility_public"],
        ["Normal Users", "always_grant"],
        ["Normal Users", "edit_wiki_pages"],
        ["Normal Users", "login"],
        ["Normal Users", "practice_tools_use"],
        ["Normal Users", "public"],
        ["Normal Users", "respond_to_events"],
        ["Normal Users", "search_users"],
        ["Normal Users", "search_wiki_pages"],
        ["Normal Users", "upload_files"],
        ["Normal Users", "view_custom_links"],
        ["Normal Users", "view_events"],
        ["Normal Users", "view_events_nonpublic"],
        ["Normal Users", "view_events_reports"],
        ["Normal Users", "view_files"],
        ["Normal Users", "view_songs"],
        ["Normal Users", "view_users_basic_info"],
        ["Normal Users", "view_wiki_pages"],
        ["Normal Users", "visibility_logged_in_users"],
        ["Normal Users", "visibility_members"],
        ["Normal Users", "visibility_public"],
        ["Public", "always_grant"],
        ["Public", "practice_tools_use"],
        ["Public", "public"],
        ["Public", "view_events"],
        ["Public", "view_files"],
        ["Public", "visibility_public"],
        ["Public", "view_wiki_pages"],
    ]
    ;
