// used by seeding, and by runtime permission seeds.

export const DefaultRolePermissionAssignments: ReadonlyArray<[string, string]> =
    [
        ["Editors", "access_file_landing_page"],
        ["Moderators", "access_file_landing_page"],
        ["Band Admin", "access_file_landing_page"],
        ["Admin", "access_file_landing_page"],
        ["Moderators", "admin_wiki_pages"],
        ["Band Admin", "admin_wiki_pages"],
        ["Admin", "admin_wiki_pages"],
        ["Admin", "admin_workflow_defs"],
        ["Public", "always_grant"],
        ["Limited Users", "always_grant"],
        ["Normal Users", "always_grant"],
        ["Editors", "always_grant"],
        ["Moderators", "always_grant"],
        ["Band Admin", "always_grant"],
        ["Admin", "always_grant"],
        ["Moderators", "change_others_event_responses"],
        ["Band Admin", "change_others_event_responses"],
        ["Admin", "change_others_event_responses"],
        ["Moderators", "customize_menu"],
        ["Band Admin", "customize_menu"],
        ["Admin", "customize_menu"],
        ["Normal Users", "edit_wiki_pages"],
        ["Editors", "edit_wiki_pages"],
        ["Moderators", "edit_wiki_pages"],
        ["Band Admin", "edit_wiki_pages"],
        ["Admin", "edit_wiki_pages"],
        ["Moderators", "edit_workflow_defs"],
        ["Band Admin", "edit_workflow_defs"],
        ["Admin", "edit_workflow_defs"],
        ["Editors", "edit_workflow_instances"],
        ["Moderators", "edit_workflow_instances"],
        ["Band Admin", "edit_workflow_instances"],
        ["Admin", "edit_workflow_instances"],
        ["Editors", "manage_custom_links"],
        ["Moderators", "manage_custom_links"],
        ["Band Admin", "manage_custom_links"],
        ["Admin", "manage_custom_links"],
        ["Editors", "pin_song_recordings"],
        ["Moderators", "pin_song_recordings"],
        ["Band Admin", "pin_song_recordings"],
        ["Admin", "pin_song_recordings"],
        ["Moderators", "search_users"],
        ["Band Admin", "search_users"],
        ["Admin", "search_users"],
        ["Normal Users", "search_wiki_pages"],
        ["Editors", "search_wiki_pages"],
        ["Moderators", "search_wiki_pages"],
        ["Band Admin", "search_wiki_pages"],
        ["Admin", "search_wiki_pages"],
        ["Admin", "setlist_planner_access"],
        ["Normal Users", "view_custom_links"],
        ["Editors", "view_custom_links"],
        ["Moderators", "view_custom_links"],
        ["Band Admin", "view_custom_links"],
        ["Admin", "view_custom_links"],
        ["Normal Users", "view_events_nonpublic"],
        ["Editors", "view_events_nonpublic"],
        ["Moderators", "view_events_nonpublic"],
        ["Band Admin", "view_events_nonpublic"],
        ["Admin", "view_events_nonpublic"],
        ["Normal Users", "view_events_reports"],
        ["Editors", "view_events_reports"],
        ["Moderators", "view_events_reports"],
        ["Band Admin", "view_events_reports"],
        ["Admin", "view_events_reports"],
        ["Admin", "view_feature_reports"],
        ["Admin", "view_users_basic_info"],
        ["Editors", "view_wiki_page_revisions"],
        ["Moderators", "view_wiki_page_revisions"],
        ["Band Admin", "view_wiki_page_revisions"],
        ["Admin", "view_wiki_page_revisions"],
        ["Limited Users", "view_wiki_pages"],
        ["Normal Users", "view_wiki_pages"],
        ["Editors", "view_wiki_pages"],
        ["Moderators", "view_wiki_pages"],
        ["Band Admin", "view_wiki_pages"],
        ["Admin", "view_wiki_pages"],
        ["Admin", "view_workflow_defs"],
        ["Admin", "view_workflow_instances"],
        ["Public", "public"],
        ["Limited Users", "public"],
        ["Normal Users", "public"],
        ["Editors", "public"],
        ["Moderators", "public"],
        ["Band Admin", "public"],
        ["Admin", "public"],
        ["Limited Users", "login"],
        ["Normal Users", "login"],
        ["Editors", "login"],
        ["Moderators", "login"],
        ["Band Admin", "login"],
        ["Admin", "login"],
        ["Limited Users", "basic_trust"],
        ["Normal Users", "basic_trust"],
        ["Editors", "basic_trust"],
        ["Moderators", "basic_trust"],
        ["Band Admin", "basic_trust"],
        ["Admin", "basic_trust"],
        ["Admin", "sysadmin"],
        ["Admin", "impersonate_user"],
        ["Editors", "edit_public_homepage"],
        ["Moderators", "edit_public_homepage"],
        ["Band Admin", "edit_public_homepage"],
        ["Admin", "edit_public_homepage"],
        ["Admin", "admin_events"],
        ["Editors", "manage_events"],
        ["Moderators", "manage_events"],
        ["Band Admin", "manage_events"],
        ["Admin", "manage_events"],
        ["Public", "view_events"],
        ["Limited Users", "view_events"],
        ["Normal Users", "view_events"],
        ["Editors", "view_events"],
        ["Moderators", "view_events"],
        ["Band Admin", "view_events"],
        ["Admin", "view_events"],
        ["Normal Users", "respond_to_events"],
        ["Editors", "respond_to_events"],
        ["Moderators", "respond_to_events"],
        ["Band Admin", "respond_to_events"],
        ["Admin", "respond_to_events"],
        ["Band Admin", "admin_songs"],
        ["Admin", "admin_songs"],
        ["Editors", "manage_songs"],
        ["Moderators", "manage_songs"],
        ["Band Admin", "manage_songs"],
        ["Admin", "manage_songs"],
        ["Normal Users", "view_songs"],
        ["Editors", "view_songs"],
        ["Moderators", "view_songs"],
        ["Band Admin", "view_songs"],
        ["Admin", "view_songs"],
        ["Band Admin", "admin_files"],
        ["Admin", "admin_files"],
        ["Editors", "manage_files"],
        ["Moderators", "manage_files"],
        ["Band Admin", "manage_files"],
        ["Admin", "manage_files"],
        ["Public", "view_files"],
        ["Limited Users", "view_files"],
        ["Normal Users", "view_files"],
        ["Editors", "view_files"],
        ["Moderators", "view_files"],
        ["Band Admin", "view_files"],
        ["Admin", "view_files"],
        ["Normal Users", "upload_files"],
        ["Editors", "upload_files"],
        ["Moderators", "upload_files"],
        ["Band Admin", "upload_files"],
        ["Admin", "upload_files"],
        ["Admin", "admin_instruments"],
        ["Moderators", "manage_users"],
        ["Band Admin", "manage_users"],
        ["Admin", "manage_users"],
        ["Public", "visibility_public"],
        ["Limited Users", "visibility_public"],
        ["Normal Users", "visibility_public"],
        ["Editors", "visibility_public"],
        ["Moderators", "visibility_public"],
        ["Band Admin", "visibility_public"],
        ["Admin", "visibility_public"],
        ["Limited Users", "visibility_logged_in_users"],
        ["Normal Users", "visibility_logged_in_users"],
        ["Editors", "visibility_logged_in_users"],
        ["Moderators", "visibility_logged_in_users"],
        ["Band Admin", "visibility_logged_in_users"],
        ["Admin", "visibility_logged_in_users"],
        ["Normal Users", "visibility_members"],
        ["Editors", "visibility_members"],
        ["Moderators", "visibility_members"],
        ["Band Admin", "visibility_members"],
        ["Admin", "visibility_members"],
        ["Editors", "visibility_editors"],
        ["Moderators", "visibility_editors"],
        ["Band Admin", "visibility_editors"],
        ["Admin", "visibility_editors"]
    ]
    ;
